"""Gradient boosting re-ranker for two-stage recommendation.

This module defines a simple tree-based model that re-ranks candidate
items generated by a first-stage collaborative filtering model (e.g.,
ALS or ItemCF).

The typical usage pattern is:
    - Build a candidate set per user from ALS/ItemCF.
    - Construct a feature table with one row per (user, item) candidate.
    - Train the GBMRerankerModel on these features using a binary label
      indicating whether the candidate is the held-out ground truth.
    - Use the trained model's scores to re-rank candidates for each user.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable, Sequence

import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier


@dataclass
class GBMRerankerModel:
    """Container for a trained gradient boosting re-ranker."""

    gbm: GradientBoostingClassifier
    feature_columns: list[str]


def train_reranker(
    train_df: pd.DataFrame,
    feature_columns: Sequence[str],
    label_column: str = "label",
    random_state: int | None = 42,
) -> GBMRerankerModel:
    """Fit a gradient boosting re-ranker on candidate features.

    Parameters
    ----------
    train_df:
        DataFrame with candidate rows and features.
    feature_columns:
        Names of numeric feature columns used as model inputs.
    label_column:
        Name of the binary label column (1 = ground-truth item).
    random_state:
        Seed for reproducibility.
    """
    x = train_df[list(feature_columns)].to_numpy(dtype=np.float32, copy=False)
    y = train_df[label_column].to_numpy(dtype=np.int32, copy=False)

    gbm = GradientBoostingClassifier(random_state=random_state)
    gbm.fit(x, y)

    return GBMRerankerModel(gbm=gbm, feature_columns=list(feature_columns))


def score_candidates(
    model: GBMRerankerModel,
    candidates_df: pd.DataFrame,
) -> np.ndarray:
    """Return re-ranking scores for candidate rows.

    The output is the predicted probability of label=1 (positive).
    """
    x = candidates_df[model.feature_columns].to_numpy(dtype=np.float32, copy=False)
    proba = model.gbm.predict_proba(x)
    # Column 1 corresponds to the positive class.
    return proba[:, 1]

